Add JDK11

diff --git a/Dockerfile.jdk12-dc b/Dockerfile.jdk12-dc
--- a/Dockerfile.jdk12-dc
+++ b/Dockerfile.jdk12-dc
@@ -1,23 +1,101 @@
 FROM debian
 
 ## Heavy-weight container with:
-# OpenJDK 12
+# OpenJDK 8-12
 # Docker CE
 # Docker Compose 1.24.1
 
 ENV JAVA_HOME=/usr/java/openjdk-12 \
     PATH=$JAVA_HOME/bin:$PATH \
+    JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8" \
+    LANG=C.UTF-8 \
     JAVA_VERSION=12 \
     JAVA_URL=https://download.java.net/java/GA/jdk12/GPL/openjdk-12_linux-x64_bin.tar.gz \
     JAVA_SHA256=b43bc15f4934f6d321170419f2c24451486bc848a2179af5e49d10721438dd56 \
+    JAVA11_HOME=/usr/local/openjdk-11 \
+    JAVA11_VERSION=11.0.4 \
+    JAVA11_BASE_URL=https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.4%2B11/OpenJDK11U-jdk_ \
+    JAVA11_URL_VERSION=11.0.4_11 \
     DOCKER_COMPOSE_VERSION=1.24.1 \
-    DOCKER_COMPOSE_MD5=7048a965a86e6eed1622e0990e9a7ab4 \
-    JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8" \
-    LANG=C.UTF-8
+    DOCKER_COMPOSE_MD5=7048a965a86e6eed1622e0990e9a7ab4
 
 RUN set -eux; \
   apt-get update; \
-  apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl gnupg2 software-properties-common acl gzip tar git; \
+  apt-get install -y --no-install-recommends apt-transport-https ca-certificates p11-kit curl gnupg2 software-properties-common acl gzip tar git; \
+  \
+## JDK 11 ##
+# https://github.com/docker-library/openjdk/blob/e7c6ade3d9d636c39fbbfa30c144a93fbb038494/11/jdk/slim/Dockerfile
+  \
+	dpkgArch="$(dpkg --print-architecture)"; \
+	case "$dpkgArch" in \
+		amd64) upstreamArch='x64' ;; \
+		arm64) upstreamArch='aarch64' ;; \
+		*) echo >&2 "error: unsupported architecture: $dpkgArch" ;; \
+	esac; \
+	\
+	savedAptMark="$(apt-mark showmanual)"; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+		dirmngr \
+		gnupg \
+		wget \
+	; \
+	rm -rf /var/lib/apt/lists/*; \
+	\
+	wget -O openjdk.tgz.asc "${JAVA11_BASE_URL}${upstreamArch}_linux_${JAVA11_URL_VERSION}.tar.gz.sign"; \
+	wget -O openjdk.tgz "${JAVA11_BASE_URL}${upstreamArch}_linux_${JAVA11_URL_VERSION}.tar.gz" --progress=dot:giga; \
+	\
+	export GNUPGHOME="$(mktemp -d)"; \
+# TODO find a good link for users to verify this key is right (https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2019-April/000951.html is one of the only mentions of it I can find); perhaps a note added to https://adoptopenjdk.net/upstream.html would make sense?
+	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys CA5F11C6CE22644D42C6AC4492EF8D39DC13168F; \
+# https://github.com/docker-library/openjdk/pull/322#discussion_r286839190
+	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys EAC843EBD3EFDB98CC772FADA5CD6035332FA671; \
+	gpg --batch --list-sigs --keyid-format 0xLONG CA5F11C6CE22644D42C6AC4492EF8D39DC13168F | grep '0xA5CD6035332FA671' | grep 'Andrew Haley'; \
+	gpg --batch --verify openjdk.tgz.asc openjdk.tgz; \
+	gpgconf --kill all; \
+	rm -rf "$GNUPGHOME"; \
+	\
+	mkdir -p "$JAVA11_HOME"; \
+	tar --extract \
+		--file openjdk.tgz \
+		--directory "$JAVA11_HOME" \
+		--strip-components 1 \
+		--no-same-owner \
+	; \
+	rm openjdk.tgz*; \
+	\
+# TODO strip "demo" and "man" folders?
+	\
+	apt-mark auto '.*' > /dev/null; \
+	[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark > /dev/null; \
+	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+	\
+# update "cacerts" bundle to use Debian's CA certificates (and make sure it stays up-to-date with changes to Debian's store)
+# see https://github.com/docker-library/openjdk/issues/327
+#     http://rabexc.org/posts/certificates-not-working-java#comment-4099504075
+#     https://salsa.debian.org/java-team/ca-certificates-java/blob/3e51a84e9104823319abeb31f880580e46f45a98/debian/jks-keystore.hook.in
+#     https://git.alpinelinux.org/aports/tree/community/java-cacerts/APKBUILD?id=761af65f38b4570093461e6546dcf6b179d2b624#n29
+	{ \
+		echo '#!/usr/bin/env bash'; \
+		echo 'set -Eeuo pipefail'; \
+		echo 'if ! [ -d "$JAVA11_HOME" ]; then echo >&2 "error: missing JAVA11_HOME environment variable"; exit 1; fi'; \
+# 8-jdk uses "$JAVA11_HOME/jre/lib/security/cacerts" and 8-jre and 11+ uses "$JAVA11_HOME/lib/security/cacerts" directly (no "jre" directory)
+		echo 'cacertsFile=; for f in "$JAVA11_HOME/lib/security/cacerts" "$JAVA11_HOME/jre/lib/security/cacerts"; do if [ -e "$f" ]; then cacertsFile="$f"; break; fi; done'; \
+		echo 'if [ -z "$cacertsFile" ] || ! [ -f "$cacertsFile" ]; then echo >&2 "error: failed to find cacerts file in $JAVA11_HOME"; exit 1; fi'; \
+		echo 'trust extract --overwrite --format=java-cacerts --filter=ca-anchors --purpose=server-auth "$cacertsFile"'; \
+	} > /etc/ca-certificates/update.d/docker-openjdk; \
+	chmod +x /etc/ca-certificates/update.d/docker-openjdk; \
+	/etc/ca-certificates/update.d/docker-openjdk; \
+	\
+# https://github.com/docker-library/openjdk/issues/331#issuecomment-498834472
+	find "$JAVA11_HOME/lib" -name '*.so' -exec dirname '{}' ';' | sort -u > /etc/ld.so.conf.d/docker-openjdk.conf; \
+	ldconfig; \
+	\
+# basic smoke test
+	$JAVA11_HOME/bin/javac --version; \
+	$JAVA11_HOME/bin/java --version; \
+  \
+## JDK 12 ##
   \
 # https://github.com/docker-library/openjdk/blob/bf1072ab57caa868bbe13683ca4e9e6169010f05/12/jdk/oracle/Dockerfile#L21-L32
 	\
